# One Dimensional

In [1]:
import numpy as np

a=np.array([10,20,30])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [2]:
print(a)

[10 20 30]


In [3]:
print(a[0])

10


In [4]:
a[0]=50

In [5]:
a

array([50, 20, 30])

# 2-Dimensional

In [6]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
print(b.shape)

(2, 3)


In [8]:
print(b[1,2],b[0,1])

6 2


In [9]:
b[0,2]

3

# 3-Dimensional

In [10]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])

c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print(c.shape)

(3, 3)


In [12]:
print(c[2,0])

7


In [13]:
c[1,2]

6

In [14]:
a=np.zeros((2,2))
print(a)

a.shape

[[0. 0.]
 [0. 0.]]


(2, 2)

In [15]:
b=np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
c=np.full((3,3),3)
print(c)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [17]:
d=np.eye(6)
print(d)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [18]:
e=np.random.random((3,2))

print(e)

[[0.08448913 0.01374046]
 [0.61152483 0.22591532]
 [0.65824932 0.81402667]]


In [19]:
f=np.arange(0,21,3)
f

array([ 0,  3,  6,  9, 12, 15, 18])

In [20]:
g=np.linspace(0,5,10)
g

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
import numpy as np
arr=np.array([[1,2,3,4],
             [5,2,4,2],
             [1,2,0,1]])

newarr=arr.reshape(2,2,3)

print("\nOriginal array:\n",arr)

print("Reshaped array:\n",newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [22]:
a=np.array([[1,2,3],[4,5,6]])
flarr=a.flatten()

print("\nOriginal array:\n",a)

print("Fattened array:\n",flarr)


Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


# Slicing Array

In [23]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
b=a[0:2,1:3]

b

array([[2, 3],
       [6, 7]])

In [25]:
print(a[1,1])

6


In [26]:
a[0,1]=77

a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
row_r1=a[2,:]
row_r2=a[1,:]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[ 9 10 11 12] (4,)
[5 6 7 8] (4,)


In [29]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
a[0,]

array([1, 2, 3, 4])

In [31]:
col_r1=a[:,1]
col_r1


array([ 2,  6, 10])

In [32]:
col_r2=a[:,2:]
col_r2

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [33]:
print(col_r1,col_r1.shape)
print(col_r2,col_r2.shape)

[ 2  6 10] (3,)
[[ 3  4]
 [ 7  8]
 [11 12]] (3, 2)


# Integer array indexing

In [34]:
a=np.array([[-1,2,0,4],
           [4,-0.5,6,0],
           [2.6,0,7,8],
           [3,-7,4,2.0]])
a

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [35]:
temp=a[[0,1,2,3],[3,2,1,0]]
print("\nElements at indices (0,3),(1,2),(2,1),""(3,0):\n",temp)


Elements at indices (0,3),(1,2),(2,1),(3,0):
 [4. 6. 0. 3.]


# Boolean array

In [36]:
a

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [37]:
cond=a > 0
cond

array([[False,  True, False,  True],
       [ True, False,  True, False],
       [ True, False,  True,  True],
       [ True, False,  True,  True]])

In [38]:
cond=a%2==0
temp=a[cond]

print("\nElements greater than 0:\n",temp)


Elements greater than 0:
 [2. 0. 4. 4. 6. 0. 0. 8. 4. 2.]


In [39]:
a=np.array([1,2,5,3])
print("Original element:",a)

print("Adding 1 to every element:",a+1)

print("Subtracting 3 from each element:",a-3)

print("Multiplying each element by 10:",a*10)

print("Squaring each element:",a**2)

a *= 2
print("Doubled each element of original array:",a)

a=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("\nOriginal array:\n",a)

print("Transpose of array:\n",a.T)


Original element: [1 2 5 3]
Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


# Unary Operators

In [40]:
arr=np.array([[1,5,6],
            [4,7,2],
            [3,1,9]])

print("Largest element is:",arr.max())

print("Row-wise maximum elements:",arr.max(axis=1))

print("Column-wise maximum elements:",arr.max(axis=0))

print("Sum of all array elements:",arr.sum())

print("Cumulative sum along each row:\n",arr.cumsum(axis=1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise maximum elements: [4 7 9]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


# Binary Operators

In [41]:
a=np.array([[1,2],
           [3,4]])
b=np.array([[4,3],
           [2,1]])

print("Array sum:\n",a+b)

print("Array multiplication:\n",a*b)

print("Matrix multiplication:\n",a.dot(b))



Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [42]:
a=np.array([25,16,4,9])
print("Exponent of array elements:",np.log(a))

print("Square root of array elements:",np.sqrt(a))

Exponent of array elements: [3.21887582 2.77258872 1.38629436 2.19722458]
Square root of array elements: [5. 4. 2. 3.]


# Sorting array: There is asimple 

In [43]:
a=np.array([[1,4,2],
          [3,4,6],
          [0,-1,5]])
print("Array elemets in sorted order:\n",np.sort(a,axis=None))

Array elemets in sorted order:
 [-1  0  1  2  3  4  4  5  6]


In [44]:
print("Column-wise sorted array:\n",np.sort(a,axis=0))

Column-wise sorted array:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [45]:
print("Row-wise sort by applying merge-sort:\n",np.sort(a,axis=1))

Row-wise sort by applying merge-sort:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]


# Finished